#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int CR;
int threshold = 65; // 100 =w hite | 0 = black
int Rspeed = 0;
int Lspeed = 0;
int state = 1;
int fase = 0;
int fase1time = 4300;
int fase2time = 9500;
int fase3time = 999999;
string message = " ";


task MotorTask()
{
	while(1)
	{
		setMotorSpeed(motorB, Lspeed);
		setMotorSpeed(motorC, Rspeed);
		sleep(50); // 20Hz = 1000/20
	}
}


setMotorSync(nMotorOne, nMotorTwo, nTurnRatio, nSignedPower);


task DisplayTask()
{
	while(1)
	{
		displayTextLine(1, message);
		displayTextLine(2,"ColorReflected: %d", CR);
		displayTextLine(3,"state: %d", state);
		displayTextLine(4, "Rspeed: %d", Rspeed);
		displayTextLine(5, "Lspeed: %d", Lspeed);
		displayTextLine(6,"time: %d",time1[T1]);
		displayTextLine(7,"fase: %d",fase);
		sleep(200); // 5Hz = 1000/5
	}
}

task ColorReflected{
	while(1){
		CR = getColorReflected(colorSensor);
		sleep(10);// 20Hz = 1000/20
	}
}


task main()
{while(getUSDistance(S4) > 4) //get near the box
{
	setMotorSpeed(motorB, 60);
	setMotorSpeed(motorC, 60);
}
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
	sleep(500);
	setMotorSpeed(motorA, -50);	//grab the box

  startTask(MotorTask);
	startTask(DisplayTask);
	startTask(ColorReflected);


	clearTimer(T1);


  while(true)
  {
  	if(fase1time >= time1[T1])
  		fase = 1;																			//follow the line along the right side
  	else if(fase2time >= time1[T1] && CR < threshold)
  		fase = 2;																			//follow the line along the left  side
  	else if(fase3time >= time1[T1] && CR < threshold)
  		fase = 3;																			//follow the line along the right side slowly


  	switch(fase)
  	{
  	case 1: state = 1; break;
  	case 2: state = 3; break;
  	case 3: state = 5; break;
  	default: state = 0; break;
  	}


    switch(state)
    {
     case 1:// if in white turn left
    		 		if(CR < threshold)
    				 state = 2;
    				 break;
     case 2: //if in black turn right
    				if(CR > threshold)
    				 state = 1;
    				 break;
     case 3://if in black turn left
     				if(CR > threshold)
     					state = 4;
     					break;
     case 4: // if in white turn right
     				if(CR < threshold)
     					state = 3;
     					break;
     case 5:// if in white turn left
    		 		if(CR < threshold)
    				 state = 6;
    				 break;
     case 6: //if in black turn right
    				if(CR > threshold)
    				 state = 5;
    				 break;
    }

    switch(state)
    {
    	case 1:
    		Lspeed = 20; Rspeed = 40; break;
    	case 2:
    		Lspeed = 40; Rspeed = 20; break;
    	case 3:
    		Lspeed = 15; Rspeed = 55; break;
    	case 4:
    		Lspeed = 55; Rspeed = 15; break;
    	case 5:
    		Lspeed = 10; Rspeed = 30; break;
    	case 6:
    		Lspeed = 30; Rspeed = 10; break;
    }

  }

}
